### PR TITLE
#138 fix bug in exa.write

### LINKED ISSUE #138: R version 4,2 (April 2022!) is.na() robustness check of multiple elements causing issues in exa.writeData()
https://github.com/exasol/r-exasol/blob/main/R/exa.writeData.R#L78

```
if (is.na(tableColumns)) ""
else {paste("(",paste(tableColumns,collapse=", "),")")}
```

This no longer works in R.
In R version 4,2, `is.na()` checks are now more strict.

Before: `if (is.na(multiple_elements))` would only check first element and raise a warning about how `length(multiple_elements) > 1`.
Since R 4,2: `if (is.na(multiple_elements))` would raise fatal error.

Fix needs to address:
1. `length(tableColumns) == 1 &(& maybe?) is.na(tableColumns)`
2. `length(tableColumns) == 1 &(& maybe?) !is.na(tableColumns)`
3. `length(tableColumns) > 1`

### PR DESCRIPTION
**Pull request by tomuben**
1. fixes #138 
2. pass GITHUB_TOKEN to integration-test Docker container in order to avoid running into Github rate limit

### CODE REVIEW

File: tests/testthat/run-dbi-tests.R [hunk 1]
```diff
@@ -212,6 +212,101 @@ test_that("dbWriteTable imports dataframe with mixed characters", {
...
+
+    res <- exa.writeData(con, twogroups, tableName = schema_table)
+    expect_true(res)
+
+    result <- exa.readData(con, paste0("select * from ", schema_table))
+    expect_equal(result, twogroups)
+
+  dbDisconnect(con)
+})
+
```
Comment (morazow) [inline tests/testthat/run-dbi-tests.R:309]: :+1:

**Review by morazow — APPROVED** [review]
Looks good!
