### PR TITLE
#154: Enable encryption by default

### LINKED ISSUE #154: Enable encryption by default
Since DB version 8 encryption is enabled by default (see [Release Notes - Database](https://docs.exasol.com/db/latest/release_notes_db.htm)).

However, `r-exasol` by default establishes a non-encrypted connection, so the following kind of connection

```r
exaconn <- dbConnect(
    drv = "exa",
    exahost = "demodb.exasol.com:8563",
    uid = "<YOUR_USER>",
    pwd = "<YOUR_PASSWORD>")
```

fails with

```
Error in odbcGetInfo(con) : argument is not an open RODBC channel
In addition: Warning messages:
1: In odbcDriverConnect(con_str) :
  [RODBC] ERROR: state 28000, code -3732480, message [Exasol][Exasol Driver]Connection exception - Only TLS connections are allowed.
2: In odbcDriverConnect(con_str) : ODBC connection failed
```

Please align `r-exasol` with the current DB approach and make encryption enabled by default.

### LINKED ISSUE #157: SSL Certificate not working with cloned connection
## How to reproduce

Create a connection with parameter `sslcertificate` and clone it (For example see respective [the integration test](https://github.com/exasol/r-exasol/blob/c7560175c555ab2c102c77d9a1af8590b51bb6f0/tests/testthat/test-Connection.R#L52)).

## Root Cause Analysis
This won't work if the path of the ssl certificate has lower letters, because the clone implementation transforms the value of the ssl certificate to upper letters.

### PR DESCRIPTION
**Pull request by tomuben**
fixes #154 
fixes #157

### CODE REVIEW

File: tests/Dockerfile [hunk 1]
```diff
@@ -41,12 +41,12 @@ RUN  Rscript -e 'devtools::install_github("jimhester/lintr")'
 RUN  Rscript -e 'devtools::install_github("marcelboldt/DBI")'
 RUN  Rscript -e 'devtools::install_github("marcelboldt/DBItest")'
 
-RUN curl -L -o EXASOL_ODBC.tar.gz https://exasol-script-languages-dependencies.s3.eu-central-1.amazonaws.com/EXASOL_ODBC-7.0.11.tar.gz && \
+RUN curl -L -o EXASOL_ODBC.tar.gz https://x-up.s3.amazonaws.com/7.x/25.2.1/Exasol_ODBC-25.2.1-Linux_x86_64.tar.gz && \
```
Comment (tkilias) [inline tests/Dockerfile:44]: Nice, we can now use the official source

File: tests/scripts/execute_docker_test_env.sh [hunk 2]
```diff
@@ -19,4 +19,5 @@ SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
 docker container rm -f -v r_test || true
 IMAGE_NAME="$("$SCRIPT_DIR/construct_docker_image_complete_name.sh" "${COMBINED_R_VERSION}")"
 PROJ_DIR="$(realpath "$SCRIPT_DIR/../..")"
-docker run  --network host --name r_test -v "$PROJ_DIR":"$PROJ_DIR" -t "$IMAGE_NAME" "$PROJ_DIR" "$VARIANT"
\ No newline at end of file
+CERTIFICATE_PATH=${R_TESTS_CERTIFICATE_PATH:-/tmp/certificate/}
+docker run  --network host --name r_test -v "$PROJ_DIR":"$PROJ_DIR" -v "$CERTIFICATE_PATH":"/certificate/" --add-host exasol-test-database:127.0.0.1 -t "$IMAGE_NAME" "$PROJ_DIR" "$VARIANT"
```
Comment (tkilias) [inline tests/scripts/execute_docker_test_env.sh:23]: Uff, this is a handful, a bit explanation would be helpful

**Review by tkilias — CHANGES_REQUESTED** [review]

File: .github/workflows/windows_macosx.yml [hunk 3]
```diff
@@ -51,6 +51,12 @@ jobs:
         shell: Rscript {0}
         env:
           GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+      - name: Update deps
+        run: |
+          devtools::install_deps()
```
[the remark this answers is not in the document]
Comment (tomuben) [reply .github/workflows/windows_macosx.yml:56]: Done

File: R/EXADBI-connection.R [hunk 4]
```diff
@@ -271,9 +267,6 @@ dbCurrentSchema <- function(con, setSchema=NULL) {
     if (sslcertificate != "") {
       con_str <- paste0(con_str,";SSLCERTIFICATE=",sslcertificate)
     }
-    if (uselegacyencryption != "") {
```
[the remark this answers is not in the document]
Comment (tomuben) [reply R/EXADBI-connection.R:274]: IT's still used, but customers had enough time to switch to TLS now.
=> Let's remove it.

File: tests/scripts/execute_docker_test_env.sh (hunk 2 above)
Comment (tomuben) [reply tests/scripts/execute_docker_test_env.sh:23]: Done

**Review by tkilias — APPROVED** [review]

**Comment by allipatev** [comment]
@tomuben @tkilias 

I'm not sure that removing LEGACYENCRYPTION from `r-exasol` should have been done.

There are still situations where legacy encryption mode is the only workaround - when OpenSSL causes problems.
Even though Drivers team has a SPOT, when and if it will be fixed - we don't know.
But particular SPOT is just an example, the concept remains - ChaCha is deprecated but not removed, even from the latest DB releases.

**Comment by tomuben** [comment]
@allipatev 
It's still possible to set raw ODBC parameter in `dbConnect()`, so:
```
dbConnect("exa", exahost="exasol-test-database:8888", uid = "sys", pwd = "exasol", "USELEGACYENCRYPTION=Y")
```
could still be used in an emergency.
But as I switched the CI tests to db 8.31.0 there is no way to test the legacy encryption now, and I don't want to have a parameter in the interface which is not covered by the integration tests.

**Comment by tomuben** [comment]
@allipatev,
just to make it clear: The legacy encryption does not work anymore since db 8.19.0, see https://docs.exasol.com/db/latest/connect_exasol/drivers/odbc/using_odbc.htm.
